# fly.toml app configuration file generated for askteamlead-telegram-bot on 2025-06-01T13:12:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'askteamlead-telegram-bot'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '8080'
  WEBHOOK_HOST = 'https://askteamlead-telegram-bot.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
